version: 2.1
orbs:
  devops_security: prisma_cloud/devops_security@3.0.4
jobs:
  docker_safe_build:
    executor: pcs/compute
    steps:
      - checkout
      - run: docker pull nginx
      - pcs/scan_image:
          prisma_cloud_compute_password: Vz6EbtHwAhDLBZ2g9ycuHPlgq2I=
          prisma_cloud_compute_url: https://europe-west3.cloud.twistlock.com/eu-1610258
          prisma_cloud_compute_username: bbd7ac3c-9002-47ac-bbd8-cc5ddebffb3c
          prisma_cloud_scan_image: nginx

